__all__ = (
    'BOOK_GENRES',
)

BOOK_GENRES = [
    "Children's",
    'Action and Adventure',
    'Anthology',
    'Art',
    'Autobiographies',
    'Biographies',
    'Comics',
    'Cookbooks',
    'Diaries',
    'Dictionaries',
    'Drama',
    'Encyclopedias',
    'Fantasy',
    'Guide',
    'Health',
    'History',
    'Horror',
    'Journals',
    'Math',
    'Mystery',
    'Poetry',
    'Prayer books',
    'Religion, Spirituality & New Age',
    'Romance',
    'Satire',
    'Science fiction',
    'Science',
    'Self help',
    'Series',
    'Travel',
    'Trilogy',
]
