# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-18 20:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20170322_2001'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='publisher',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='author',
            name='headshot',
            field=models.ImageField(blank=True, null=True, upload_to='authors'),
        ),
    ]
