# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-19 12:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_book_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='state',
            field=models.CharField(choices=[('pulished', 'Published'), ('not_published', 'Not published'), ('in_progress', 'In progress'), ('canelled', 'Cancelled'), ('rejected', 'Rejected')], default='pulished', max_length=100),
        ),
    ]
