# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-20 21:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_auto_20170823_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='lon',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=19, null=True),
        ),
    ]
