# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-21 20:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_auto_20170920_1607'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='book',
            name='lon',
        ),
        migrations.AddField(
            model_name='publisher',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=15, default=0, max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='publisher',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=15, default=0, max_digits=19, null=True),
        ),
    ]
