# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-03 19:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0013_auto_20171003_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
