# Generated by Django 3.1.6 on 2021-02-19 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0018_auto_20210203_1549'),
        ('books', '0018_auto_20200916_1549'),
    ]

    operations = [
    ]
