BOOK_PUBLISHING_STATUS_PUBLISHED = 'published'
BOOK_PUBLISHING_STATUS_NOT_PUBLISHED = 'not_published'
BOOK_PUBLISHING_STATUS_IN_PROGRESS = 'in_progress'
BOOK_PUBLISHING_STATUS_CANCELLED = 'cancelled'
BOOK_PUBLISHING_STATUS_REJECTED = 'rejected'
BOOK_PUBLISHING_STATUS_CHOICES = (
    (BOOK_PUBLISHING_STATUS_PUBLISHED, "Published"),
    (BOOK_PUBLISHING_STATUS_NOT_PUBLISHED, "Not published"),
    (BOOK_PUBLISHING_STATUS_IN_PROGRESS, "In progress"),
    (BOOK_PUBLISHING_STATUS_CANCELLED, "Cancelled"),
    (BOOK_PUBLISHING_STATUS_REJECTED, "Rejected"),
)
BOOK_PUBLISHING_STATUS_DEFAULT = BOOK_PUBLISHING_STATUS_PUBLISHED

YES = 'yes'
NO = 'no'

LOCATION_CATEGORY_OFFICE = 'Office'
LOCATION_CATEGORY_INDUSTRIAL = 'Industrial'
LOCATION_CATEGORY_RETAIL = 'Retail'
LOCATION_CATEGORY_LEISURE = 'Leisure'
LOCATION_CATEGORY_CHOICES = (
    (LOCATION_CATEGORY_OFFICE, LOCATION_CATEGORY_OFFICE),
    (LOCATION_CATEGORY_INDUSTRIAL, LOCATION_CATEGORY_INDUSTRIAL),
    (LOCATION_CATEGORY_RETAIL, LOCATION_CATEGORY_RETAIL),
    (LOCATION_CATEGORY_LEISURE, LOCATION_CATEGORY_LEISURE),
)
